name: Sync GitHub â†’ Azure DevOps

on:
  push:
    branches:
      - main  # only triggers when you push to 'main'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Push to Azure DevOps
        env:
          AZURE_ORG: "Infrabuild-TEST"           
          AZURE_PROJECT: "Space Game - web"   
          AZURE_PROJECT_ENCODED: "Space%Game%-%web" 
          AZURE_REPO: "hoon_test_2"         
          AZURE_PAT: ${{ secrets.AZURE_PAT }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

          git remote add azure "https://${AZURE_ORG}:${AZURE_PAT}@dev.azure.com/${AZURE_ORG}/${AZURE_PROJECT_ENCODED}/_git/${AZURE_REPO}"
          git push azure main --force
